# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: bioc-devel

addons:
  apt:
    update: true
    packages:
      - libfftw3-3

r_binary_packages:
  - covr
  - purrr
  - magrittr
  - dplyr
  - tidyr
  - abind
  - tibble
  - mixtools

cache:
  packages: true
  directories:
    - /usr/local/lib/R/site-library
    - /usr/lib/R

after_success:
  - Rscript -e 'covr::codecov()'
